#!/usr/bin/env php
<?php
/**
 * CSC 481 - Article Scraping
 *
 * @author      Dan Richards
 * @professor   Hamel
 * @term        Spring 2015
 *
 * @todo Consider AbstractScraper interface and class.
 * @todo Implement the AbstractHeuristic in our current Heuristics
 * @todo Write Santizers
 * @todo Override toJson() (a simple array of objects) method in Considerations to accommodate DOMElement properties. Follow Json standards on jsonapi.com.
 * @todo Get rid of Finder and FinderResult
 *
 * This file bootstraps all of the glorious commands we've made.
 *
 * The .php extension has been removed so we may simple type "php csc481 namespace:command --option=whatever"
 */

require __DIR__.'/vendor/autoload.php';

use Symfony\Component\Console\Application;
use AiCrawler\Commands\GreetCommand;
use AiCrawler\Commands\Test\TextCommand;
use AiCrawler\Commands\Dom\BfsCommand;
use AiCrawler\Commands\Dom\InspectCommand;
use AiCrawler\Commands\Blog\HeadlineCommand;
use AiCrawler\Commands\Blog\ContentCommand;
use AiCrawler\Commands\Blog\ImageCommand;

$application = new Application();
$application->add(new GreetCommand());
$application->add(new BfsCommand());
$application->add(new TextCommand());
$application->add(new InspectCommand());
$application->add(new HeadlineCommand());
$application->add(new ContentCommand());
$application->add(new ImageCommand());
$application->run();