#!/usr/bin/env php
<?php

/**
 * CSC 481 - Article Scraping
 *
 * @author      Dan Richards
 * @professor   Hamel
 * @term        Spring 2015
 *
 * @todo Override toJson() (a simple array of objects) method in Considerations to accommodate DOMElement properties.
 * @todo ...Follow Json standards on jsonapi.com.
 * @todo Write Santizers
 *
 * This file bootstraps all of the glorious commands we've made.
 *
 * The .php extension has been removed so we may simple type "php csc481 namespace:command --option=whatever"
 */

require __DIR__.'/vendor/autoload.php';

use Symfony\Component\Console\Application;

use Dan\AiCrawler\Console\Dom\BfsCommand;
use Dan\AiCrawler\Console\Dom\InspectCommand;
use Dan\AiCrawler\Console\Blog\HeadlineCommand;
use Dan\AiCrawler\Console\Blog\ContentCommand;
use Dan\AiCrawler\Console\Blog\ImageCommand;
use Dan\AiCrawler\Console\Blog\JsonCommand;
use Dan\AiCrawler\Console\Dom\SourceCommand;

$application = new Application();
$application->add(new BfsCommand());
$application->add(new InspectCommand());
$application->add(new HeadlineCommand());
$application->add(new ContentCommand());
$application->add(new ImageCommand());
$application->add(new JsonCommand());
$application->add(new SourceCommand());
$application->run();